spring:
  config:
    import: classpath:credentials.yml
  datasource:
    url: jdbc:mysql://localhost:3306/devDB
    username: user
    password: upassw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: pkc-9q8rv.ap-south-2.aws.confluent.cloud:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
    topics:
      reset-password-topic: sa-reset-password-email-message-dev
