version: '3.9'

services:
  database:
    image: mysql:8.0.39-debian
    container_name: database
    restart: always
    shm_size: 256mb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rpassw0rd
      MYSQL_DATABASE: devDB
      MYSQL_USER: user
      MYSQL_PASSWORD: upassw0rd
    volumes:
      - local_storage:/var/lib/mysql

volumes:
  local_storage: